# Auto-Generated by cargo-bitbake 0.3.16-alpha.0
#
inherit cargo

# If this is git based prefer versioned ones if they exist
# DEFAULT_PREFERENCE = "-1"

# how to get test-cross could be as easy as but default to a git checkout:
# SRC_URI += "crate://crates.io/test-cross/0.1.0"
SRC_URI += "git://git@github.com/opalenic/test_cross.git;protocol=ssh;nobranch=1"
SRCREV = "2d6a9347b74e61147599396a77a6304f04e300f6"
S = "${WORKDIR}/git"
CARGO_SRC_DIR = ""
PV:append = ".AUTOINC+2d6a9347b7"

# please note if you have entries that do not begin with crate://
# you must change them to how that package can be fetched
SRC_URI += " \
    crate://crates.io/byteorder/1.4.3 \
    crate://crates.io/const-sha1/0.2.0 \
    crate://crates.io/libc/0.2.112 \
    crate://crates.io/local-ip-address/0.4.4 \
    crate://crates.io/memalloc/0.1.0 \
    crate://crates.io/neli/0.5.3 \
    crate://crates.io/proc-macro2/1.0.34 \
    crate://crates.io/quote/1.0.10 \
    crate://crates.io/syn/1.0.84 \
    crate://crates.io/thiserror-impl/1.0.30 \
    crate://crates.io/thiserror/1.0.30 \
    crate://crates.io/unicode-xid/0.2.2 \
    crate://crates.io/windows/0.18.0 \
    crate://crates.io/windows_gen/0.18.0 \
    crate://crates.io/windows_macros/0.18.0 \
"



# FIXME: update generateme with the real MD5 of the license file
LIC_FILES_CHKSUM = " \
    file://LICENSE;md5=d8e8fca2dc0f896fd7cb4cb0031ba249 \
"

SUMMARY = "Lorem ipsum"
HOMEPAGE = "https://github.com/opalenic/test_cross.git"
LICENSE = "BSD"

# includes this file if it exists but does not fail
# this is useful for anything you may want to override from
# what cargo-bitbake generates.
include test-cross-${PV}.inc
include test-cross.inc
