# # Auto-Generated by cargo-bitbake 0.3.16-alpha.0
# #
# inherit cargo

# # If this is git based prefer versioned ones if they exist
# # DEFAULT_PREFERENCE = "-1"

# # how to get test-cross could be as easy as but default to a git checkout:
# # SRC_URI += "crate://crates.io/test-cross/0.1.0"
# SRC_URI += "git://github.com/opalenic/test_cross.git;protocol=https;nobranch=1"
# SRCREV = "4dbc89a0c693a612b0c665baabae2f6771f07048"
# S = "${WORKDIR}/git"
# CARGO_SRC_DIR = ""
# PV_append = ".AUTOINC+4dbc89a0c6"

# # please note if you have entries that do not begin with crate://
# # you must change them to how that package can be fetched
# SRC_URI += " \
# "



# # FIXME: update generateme with the real MD5 of the license file
# LIC_FILES_CHKSUM = " \
#     file://LICENSE;md5=d8e8fca2dc0f896fd7cb4cb0031ba249 \
# "

# SUMMARY = "Lorem ipsum"
# HOMEPAGE = "https://github.com/opalenic/test_cross.git"
# LICENSE = "BSD"

# # includes this file if it exists but does not fail
# # this is useful for anything you may want to override from
# # what cargo-bitbake generates.
# include test-cross-${PV}.inc
# include test-cross.inc





inherit cargo

SUMMARY = "test cross description"
HOMEPAGE = "https://github.com/opalenic/test_cross.git"
LICENSE = "MIT"

# SRC_URI = "git://github.com/opalenic/test_cross.git;tag=${PV}"
SRC_URI += "git://github.com/opalenic/test_cross.git;protocol=https;nobranch=1"
SRCREV = "4dbc89a0c693a612b0c665baabae2f6771f07048"
S = "${WORKDIR}/git"



LIC_FILES_CHKSUM = " \
    file://LICENSE;md5=d8e8fca2dc0f896fd7cb4cb0031ba249 \
"
